linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - revive
    - gocritic
    - gosimple
    - unused
    - ineffassign

linters-settings:
  goimports:
    local-prefixes: github.com/your-username/pull-request-reviewer-assignment-service
  
  gocyclo:
    min-complexity: 25
  
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false

issues:
  exclude-rules:
    - path: internal/handlers/.*\.go
      linters:
        - funlen
    - path: internal/service/.*\.go
      linters:
        - gosec

output:
  format: colored-line-number
